/* Smart Attendance V8 — dashboard
   Firebase Realtime Database + Authentication + EmailJS queue worker.
   No unknown-card database page: unknown UIDs are never written by the ESP.
*/
const firebaseConfig={apiKey:"AIzaSyCbXl2g44MRTRkm-RPM1PhiBH6RyLz6c54",authDomain:"rfid-attendance-system-a2579.firebaseapp.com",databaseURL:"https://rfid-attendance-system-a2579-default-rtdb.europe-west1.firebasedatabase.app",projectId:"rfid-attendance-system-a2579",storageBucket:"rfid-attendance-system-a2579.firebasestorage.app",messagingSenderId:"966380072300",appId:"1:966380072300:web:10bcc4db00e3efa2161749"};
const EMAILJS_PUBLIC_KEY="nD9B93LD0KsLyMDJD",EMAILJS_SERVICE_ID="service_41an7q7",EMAILJS_TEMPLATE_ID="template_o32g1yo";
firebase.initializeApp(firebaseConfig);const auth=firebase.auth(),db=firebase.database();if(window.emailjs&&!EMAILJS_PUBLIC_KEY.startsWith("YOUR_"))emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});
const $=id=>document.getElementById(id),today=()=>{const d=new Date();return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kigali'}).format(d)};
let currentUser=null,role="viewer",students={},teachers={},studentStatuses={},teacherStatuses={},history={},notifications={},settings={},users={};let listenersStarted=false;
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function toast(m){$("toast").textContent=m;$("toast").style.display="block";setTimeout(()=>$("toast").style.display="none",2800)}
function isAdmin(){return role==="admin"}function canManage(){return role==="admin"||role==="staff"}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const el=$('page-'+page);if(el)el.classList.add('active');document.querySelectorAll('.nav[data-page]').forEach(n=>n.classList.toggle('active',n.dataset.page===page));const title=page.charAt(0).toUpperCase()+page.slice(1);$('pageTitle').textContent=title;history.replaceState(null,'','#'+page);$('sidebar').classList.remove('open');if(page==='history'&&!$('historyDate').value)$('historyDate').value=today()}
window.go=go;
document.querySelectorAll('.nav[data-page]').forEach(n=>n.onclick=()=>go(n.dataset.page));$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'};if(localStorage.theme==='dark')document.body.classList.add('dark');$('logoutBtn').onclick=()=>auth.signOut();
setInterval(()=>{const d=new Date();$('liveClock').textContent=d.toLocaleTimeString('en-GB',{timeZone:'Africa/Kigali'});$('pageDate').textContent=d.toLocaleDateString('en-GB',{timeZone:'Africa/Kigali',weekday:'long',day:'2-digit',month:'short',year:'numeric'})},1000);
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='Signing in…';try{await auth.signInWithEmailAndPassword($('loginEmail').value.trim(),$('loginPassword').value)}catch(err){$('loginError').textContent=err.message}};
auth.onAuthStateChanged(async u=>{currentUser=u;if(!u){$('loginView').classList.remove('hidden');$('appView').classList.add('hidden');return}try{const snap=await db.ref('users/'+u.uid).once('value');const p=snap.val();if(!p||p.active===false){await auth.signOut();$('loginError').textContent='This account has no active dashboard role.';return}role=p.role||'viewer';$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userName').textContent=p.name||u.email||'User';$('helloName').textContent=(p.name||u.email||'User').split(' ')[0];$('avatar').textContent=(p.name||u.email||'U').charAt(0).toUpperCase();$('roleBadge').textContent=role.toUpperCase();document.querySelectorAll('.admin-only').forEach(x=>x.style.display=isAdmin()?'':'none');startListeners();}catch(e){$('loginView').classList.remove('hidden');$('loginError').textContent='Access check failed: '+e.message}});
function startListeners(){if(listenersStarted)return;listenersStarted=true;db.ref('students').on('value',s=>{students=s.val()||{};renderAll()});db.ref('teachers').on('value',s=>{teachers=s.val()||{};renderAll()});db.ref('studentStatus').on('value',s=>{studentStatuses=s.val()||{};renderAll()});db.ref('teacherStatus').on('value',s=>{teacherStatuses=s.val()||{};renderAll()});db.ref('settings').on('value',s=>{settings=s.val()||{};renderSettings()});db.ref('notificationQueue').limitToLast(200).on('value',s=>{notifications=s.val()||{};renderNotifications()});if(isAdmin())db.ref('users').on('value',s=>{users=s.val()||{};renderUsers()});db.ref('device/heartbeat').on('value',s=>renderDevice(s.val()||{}));processQueue();setInterval(processQueue,15000);cleanupSent(false)}
function statusLabel(s){const m={AT_SCHOOL:'Present',LATE:'Late',LEFT_TEMP:'Temporary outside',RETURNED:'Returned',LEFT_FINAL:'Final exit',SICK:'Sick',EXCUSED:'Excused',NOT_ARRIVED:'Not arrived'};return m[s]||'Not arrived'}
function statusClass(s){if(s==='AT_SCHOOL'||s==='RETURNED')return'good';if(s==='LATE'||s==='LEFT_TEMP')return'warn';if(s==='LEFT_FINAL'||s==='SICK')return'info';if(s==='EXCUSED')return'neutral';return'bad'}
function badge(s){return `<span class="badge-status ${statusClass(s)}">${esc(statusLabel(s))}</span>`}
function renderAll(){renderHome();renderStudents();renderTeachers();renderMorning();renderAfternoon();renderNotifications()}
function currentStatus(uid){const s=studentStatuses[uid]||{};return s.date===today()?(s.status||'NOT_ARRIVED'):'NOT_ARRIVED'}
function teacherStatus(uid){const s=teacherStatuses[uid]||{};return s.date===today()?(s.status||'NOT_ARRIVED'):'NOT_ARRIVED'}
function counts(){let c={present:0,not:0,late:0,temp:0,returned:0,final:0,sick:0,excused:0};Object.keys(students).forEach(uid=>{const s=currentStatus(uid);if(['AT_SCHOOL'].includes(s))c.present++;else if(s==='LATE')c.late++;else if(s==='LEFT_TEMP')c.temp++;else if(s==='RETURNED')c.returned++;else if(s==='LEFT_FINAL')c.final++;else if(s==='SICK')c.sick++;else if(s==='EXCUSED')c.excused++;else c.not++});return c}
function renderHome(){const c=counts();$('mPresent').textContent=c.present+ c.returned;$('mNotArrived').textContent=c.not;$('mLate').textContent=c.late;$('mTemp').textContent=c.temp;$('mReturned').textContent=c.returned;$('mFinal').textContent=c.final;const rows=Object.entries(students).map(([uid,s])=>({uid,s,st:studentStatuses[uid]||{}})).sort((a,b)=>String(b.st.time||'').localeCompare(String(a.st.time||''))).slice(0,20);$('liveTable').querySelector('tbody').innerHTML=rows.map(x=>`<tr onclick="openReport('${esc(x.uid)}')"><td><b>${esc(x.s.name)}</b></td><td>${esc(x.s.grade||x.s.class||'')}</td><td>${badge(currentStatus(x.uid))}</td><td>${esc(x.st.action||'—')}</td><td>${esc(x.st.time||'—')}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">No students registered.</td></tr>'}
function renderDevice(d){const online=d.lastSeen&&(Date.now()-new Date(d.lastSeen).getTime()<120000);$('devicePill').textContent=online?'● Machine online':'● Machine offline';$('devicePill').style.color=online?'#7ee2b8':'#f6ad55';$('connectionPill').textContent=online?'Machine online':'Machine offline';$('systemStatus').innerHTML=`<div class="status-row"><span>Wi‑Fi</span><b>${d.wifiConnected?'Connected':'Offline'}</b></div><div class="status-row"><span>Firebase</span><b>${d.firebaseConnected?'Connected':'Offline'}</b></div><div class="status-row"><span>NTP</span><b>${d.timeReady?'Ready':'Not ready'}</b></div><div class="status-row"><span>RFID</span><b>${d.rfidReady?'Ready':'Unknown'}</b></div><div class="status-row"><span>IP</span><b>${esc(d.ip||'—')}</b></div><div class="status-row"><span>Cache</span><b>${esc(d.registryCount||'—')} / 20</b></div>`}
function filteredEntries(obj,search){const q=(search||'').toLowerCase();return Object.entries(obj).filter(([uid,v])=>(uid+' '+Object.values(v||{}).join(' ')).toLowerCase().includes(q))}
function actionButtons(uid,type){if(!isAdmin())return `<button onclick="openReport('${esc(uid)}')">Details</button>`;if(type==='student')return `<button onclick="openReport('${esc(uid)}')">Details</button><button onclick="editStudent('${esc(uid)}')">Edit</button><button onclick="setException('${esc(uid)}','SICK')">Sick</button><button onclick="setException('${esc(uid)}','EXCUSED')">Excuse</button><button onclick="clearException('${esc(uid)}')">Clear</button><button onclick="deleteStudent('${esc(uid)}')">Delete</button>`;return `<button onclick="openTeacherReport('${esc(uid)}')">Details</button><button onclick="editTeacher('${esc(uid)}')">Edit</button><button onclick="setTeacherException('${esc(uid)}','SICK')">Sick</button><button onclick="setTeacherException('${esc(uid)}','EXCUSED')">Excuse</button><button onclick="clearTeacherException('${esc(uid)}')">Clear</button><button onclick="deleteTeacher('${esc(uid)}')">Delete</button>`}
function renderStudents(){const q=$('studentSearch').value;const rows=filteredEntries(students,q);$('studentsTable').querySelector('tbody').innerHTML=rows.map(([uid,s])=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.grade||s.class||'')}</td><td><code>${esc(uid)}</code></td><td>${badge(currentStatus(uid))}</td><td>${esc(s.parentEmail||'—')}</td><td><div class="action-row">${actionButtons(uid,'student')}</div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No matching students.</td></tr>'}
function renderTeachers(){const q=$('teacherSearch').value;const rows=filteredEntries(teachers,q);$('teachersTable').querySelector('tbody').innerHTML=rows.map(([uid,t])=>`<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.subject||t.role||'')}</td><td><code>${esc(uid)}</code></td><td>${badge(teacherStatus(uid))}</td><td>${t.fixedSchedule===false?'Flexible':esc((t.startTime||settings.schoolStart||'08:00')+' – '+(t.homeTime||settings.homeTime||'16:00'))}</td><td><div class="action-row">${actionButtons(uid,'teacher')}</div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">No matching teachers.</td></tr>'}
function renderMorning(){const q=$('morningSearch').value.toLowerCase(),f=$('morningFilter').value;const rows=Object.entries(students).filter(([uid,s])=>(uid+' '+s.name+' '+(s.grade||'')).toLowerCase().includes(q)).filter(([uid])=>f==='all'||currentStatus(uid)===f);$('morningTable').querySelector('tbody').innerHTML=rows.map(([uid,s])=>{const st=studentStatuses[uid]||{};return `<tr><td>${esc(s.name)}</td><td>${esc(s.grade||'')}</td><td>${badge(currentStatus(uid))}</td><td>${esc(st.time||'—')}</td><td><button class="small" onclick="openReport('${esc(uid)}')">Details</button></td></tr>`}).join('')||'<tr><td colspan="5" class="muted">No records.</td></tr>'}
function renderAfternoon(){const q=$('afternoonSearch').value.toLowerCase(),f=$('afternoonFilter').value;const rows=Object.entries(students).filter(([uid,s])=>(uid+' '+s.name+' '+(s.grade||'')).toLowerCase().includes(q)).filter(([uid])=>f==='all'||currentStatus(uid)===f);$('afternoonTable').querySelector('tbody').innerHTML=rows.map(([uid,s])=>{const st=studentStatuses[uid]||{};return `<tr><td>${esc(s.name)}</td><td>${esc(s.grade||'')}</td><td>${badge(currentStatus(uid))}</td><td>${esc(st.time||'—')}</td><td><button class="small" onclick="openReport('${esc(uid)}')">Details</button></td></tr>`}).join('')||'<tr><td colspan="5" class="muted">No records.</td></tr>'}
function renderNotifications(){let arr=Object.entries(notifications).sort((a,b)=>(b[1].timestamp||0)-(a[1].timestamp||0));let q=arr.filter(([,n])=>!n.sent&&!n.failed).length,s=arr.filter(([,n])=>n.sent).length,f=arr.filter(([,n])=>n.failed&&!n.sent).length;$('nQueued').textContent=q;$('nSent').textContent=s;$('nFailed').textContent=f;$('notificationsTable').querySelector('tbody').innerHTML=arr.slice(0,100).map(([id,n])=>`<tr><td>${esc(n.email||n.to_email||'')}</td><td>${esc(n.event||n.action||'')}</td><td>${esc(n.message||'')}</td><td>${n.sent?'<span class="badge-status good">Sent</span>':n.failed?'<span class="badge-status bad">Failed</span>':'<span class="badge-status warn">Queued</span>'}</td><td>${n.attempts||0}</td><td>${isAdmin()&&!n.sent?`<button class="small" onclick="sendQueued('${esc(id)}')">Retry</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">Queue is empty.</td></tr>'}
function renderSettings(){const v=settings||{};$('setMorningOpen').value=v.morningOpen||'05:00';$('setSchoolStart').value=v.schoolStart||'08:00';$('setHomeTime').value=v.homeTime||'16:00';$('setEveningClose').value=v.eveningClose||'19:00';$('setScanInterval').value=v.scanInterval||60;$('setAdminEmail').value=v.adminNotifyEmail||'';$('setNotifyAdmin').checked=v.notifyAdmin!==false;$('setNotifyTeachers').checked=!!v.notifyTeachers;['Arrival','Late','Exit','Return','Sick','Teacher'].forEach(x=>{const id='ev'+x;if($(id))$(id).checked=v['event'+x]!==false})}
function renderUsers(){if(!isAdmin())return;$('usersTable').querySelector('tbody').innerHTML=Object.entries(users).map(([uid,u])=>`<tr><td><code>${esc(uid)}</code></td><td>${esc(u.email||'')}</td><td>${esc(u.role||'viewer')}</td><td>${u.active===false?'No':'Yes'}</td><td>${esc(u.updatedAt||u.createdAt||'')}</td></tr>`).join('')}
async function loadHistory(){const d=$('historyDate').value||today();const snap=await db.ref('attendance/'+d).once('value');history=snap.val()||{};const rows=Object.values(history).sort((a,b)=>String(a.time||'').localeCompare(String(b.time||'')));$('historySummary').textContent=`${rows.length} events recorded on ${d}.`;$('historyTable').querySelector('tbody').innerHTML=rows.map(v=>`<tr><td>${esc(v.time||'')}</td><td>${esc(v.name||'')}</td><td>${esc(v.personType||'')}</td><td>${esc(v.grade||v.subject||'')}</td><td>${esc(v.action||'')}</td><td>${badge(v.status|| (v.late?'LATE':''))}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No attendance events.</td></tr>'}
async function loadRange(days){const end=new Date(),rows=[];for(let i=0;i<days;i++){const d=new Date(end);d.setDate(end.getDate()-i);const key=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Kigali'}).format(d);const snap=await db.ref('attendance/'+key).once('value');Object.values(snap.val()||{}).forEach(v=>rows.push({...v,date:v.date||key}))}$('historySummary').textContent=`${rows.length} events in the last ${days} days.`;$('historyTable').querySelector('tbody').innerHTML=rows.sort((a,b)=>String(b.timestamp||'').localeCompare(String(a.timestamp||''))).map(v=>`<tr><td>${esc(v.time||'')}</td><td>${esc(v.name||'')}</td><td>${esc(v.personType||'')}</td><td>${esc(v.grade||v.subject||'')}</td><td>${esc(v.action||'')}</td><td>${esc(v.date||'')}</td></tr>`).join('')}
function openStudent(){if(!isAdmin())return;$('studentModalTitle').textContent='Register student';$('studentForm').reset();$('studentForm').dataset.edit='';['nArrival','nLate','nTemp','nReturn','nFinal'].forEach(id=>$(id).checked=true);$('studentModal').classList.remove('hidden')}
function editStudent(uid){if(!isAdmin())return;const s=students[uid];$('studentModalTitle').textContent='Edit student';$('studentForm').dataset.edit=uid;$('sUid').value=uid;$('sName').value=s.name||'';$('sGrade').value=s.grade||s.class||'';$('sParent').value=s.parentEmail||'';$('sPhone').value=s.phone||'';$('nArrival').checked=s.notifyArrival!==false;$('nLate').checked=s.notifyLate!==false;$('nTemp').checked=s.notifyTemporaryExit!==false&&s.notifyExit!==false;$('nReturn').checked=s.notifyReturn!==false&&s.notifyExit!==false;$('nFinal').checked=s.notifyFinalExit!==false&&s.notifyExit!==false;$('studentModal').classList.remove('hidden')}
$('studentForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return;const uid=$('sUid').value.trim().toUpperCase(),old=e.target.dataset.edit||'';const data={name:$('sName').value.trim(),grade:$('sGrade').value.trim(),parentEmail:$('sParent').value.trim(),phone:$('sPhone').value.trim(),role:'student',active:true,notifyArrival:$('nArrival').checked,notifyLate:$('nLate').checked,notifyTemporaryExit:$('nTemp').checked,notifyReturn:$('nReturn').checked,notifyFinalExit:$('nFinal').checked};if(old&&old!==uid){await db.ref('students/'+old).remove();await db.ref('studentStatus/'+old).remove()}await db.ref('students/'+uid).set(data);await db.ref('studentStatus/'+uid).update({uid,name:data.name,grade:data.grade,status:currentStatus(uid),date:today(),updatedAt:new Date().toISOString()});closeModal('studentModal');toast('Student saved')}
async function deleteStudent(uid){if(isAdmin()&&confirm('Delete this student registration? Attendance history is kept.')){await db.ref('students/'+uid).remove();await db.ref('studentStatus/'+uid).remove();toast('Student deleted')}}
async function setException(uid,status){if(!isAdmin())return;const note=status==='SICK'?'sick':'excused';await db.ref('studentStatus/'+uid).update({status,action:status==='SICK'?'Marked sick':'Excused',exception:note,date:today(),updatedAt:new Date().toISOString()});toast('Student status updated')}
async function clearException(uid){if(!isAdmin())return;await db.ref('studentStatus/'+uid).update({status:'NOT_ARRIVED',action:'Exception cleared',exception:null,date:today(),updatedAt:new Date().toISOString()});toast('Exception cleared')}
function openTeacher(){if(!isAdmin())return;$('teacherModalTitle').textContent='Register teacher';$('teacherForm').reset();$('teacherForm').dataset.edit='';$('tFixed').checked=true;$('tStart').value=settings.schoolStart||'08:00';$('tHome').value=settings.homeTime||'16:00';['tnArrival','tnLate','tnTemp','tnReturn','tnFinal'].forEach(id=>$(id).checked=true);$('teacherModal').classList.remove('hidden')}
function editTeacher(uid){if(!isAdmin())return;const t=teachers[uid];$('teacherModalTitle').textContent='Edit teacher';$('teacherForm').dataset.edit=uid;$('tUid').value=uid;$('tName').value=t.name||'';$('tSubject').value=t.subject||t.role||'';$('tEmail').value=t.email||'';$('tFixed').checked=t.fixedSchedule!==false;$('tStart').value=t.startTime||settings.schoolStart||'08:00';$('tHome').value=t.homeTime||settings.homeTime||'16:00';$('tnArrival').checked=t.notifyArrival!==false;$('tnLate').checked=t.notifyLate!==false;$('tnTemp').checked=t.notifyTemporaryExit!==false;$('tnReturn').checked=t.notifyReturn!==false;$('tnFinal').checked=t.notifyFinalExit!==false;$('teacherModal').classList.remove('hidden')}
$('teacherForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return;const uid=$('tUid').value.trim().toUpperCase();const data={name:$('tName').value.trim(),subject:$('tSubject').value.trim(),email:$('tEmail').value.trim(),role:'teacher',active:true,fixedSchedule:$('tFixed').checked,startTime:$('tStart').value,homeTime:$('tHome').value,notifyArrival:$('tnArrival').checked,notifyLate:$('tnLate').checked,notifyTemporaryExit:$('tnTemp').checked,notifyReturn:$('tnReturn').checked,notifyFinalExit:$('tnFinal').checked};await db.ref('teachers/'+uid).set(data);closeModal('teacherModal');toast('Teacher saved')}
async function deleteTeacher(uid){if(isAdmin()&&confirm('Delete this teacher registration?')){await db.ref('teachers/'+uid).remove();await db.ref('teacherStatus/'+uid).remove();toast('Teacher deleted')}}
async function setTeacherException(uid,status){if(!isAdmin())return;await db.ref('teacherStatus/'+uid).update({status,action:status==='SICK'?'Marked sick':'Excused',exception:status==='SICK'?'sick':'excused',date:today(),updatedAt:new Date().toISOString()});toast('Teacher status updated')}
async function clearTeacherException(uid){if(!isAdmin())return;await db.ref('teacherStatus/'+uid).update({status:'NOT_ARRIVED',action:'Exception cleared',exception:null,date:today(),updatedAt:new Date().toISOString()});toast('Teacher exception cleared')}
function openReport(uid){const s=students[uid];if(!s)return;const st=studentStatuses[uid]||{};const status=currentStatus(uid);$('detailContent').innerHTML=`<div class="report-head"><div><span class="eyebrow">STUDENT REPORT CARD</span><h2>${esc(s.name)}</h2><p class="muted">${esc(s.grade||'')} • UID ${esc(uid)}</p></div>${badge(status)}</div><div class="report-kpis"><div class="report-kpi"><span>Today</span><b>${todayPercent(status)}%</b></div><div class="report-kpi"><span>Current</span><b>${esc(statusLabel(status))}</b></div><div class="report-kpi"><span>Last event</span><b>${esc(st.time||'—')}</b></div><div class="report-kpi"><span>Parent</span><b>${esc(s.parentEmail?'Set':'—')}</b></div></div><div class="panel"><h3>Today status</h3>${bar('Present',status==='AT_SCHOOL'||status==='RETURNED'?100:0)}${bar('Late',status==='LATE'?100:0)}${bar('Temporary outside',status==='LEFT_TEMP'?100:0)}${bar('Final exit',status==='LEFT_FINAL'?100:0)}${bar('Sick / excused',status==='SICK'||status==='EXCUSED'?100:0)}</div><div class="panel"><h3>Quick actions</h3><div class="action-row">${isAdmin()?`<button onclick="setException('${esc(uid)}','SICK')">Sick</button><button onclick="setException('${esc(uid)}','EXCUSED')">Excuse</button><button onclick="clearException('${esc(uid)}')">Clear exception</button>`:''}<button onclick="closeModal('detailModal');go('history')">Open history</button></div></div>`;$('detailModal').classList.remove('hidden')}
function todayPercent(status){return ['AT_SCHOOL','LATE','RETURNED'].includes(status)?100:status==='NOT_ARRIVED'?0:status==='SICK'||status==='EXCUSED'?0:100}
function bar(label,pct){return `<div class="bar-row"><span>${label}</span><div class="bar"><i style="width:${pct}%"></i></div><b>${pct}%</b></div>`}
function openTeacherReport(uid){const t=teachers[uid],st=teacherStatuses[uid]||{};if(!t)return;$('detailContent').innerHTML=`<div class="report-head"><div><span class="eyebrow">TEACHER REPORT</span><h2>${esc(t.name)}</h2><p class="muted">${esc(t.subject||'')} • UID ${esc(uid)}</p></div>${badge(teacherStatus(uid))}</div><div class="report-kpis"><div class="report-kpi"><span>Today</span><b>${todayPercent(teacherStatus(uid))}%</b></div><div class="report-kpi"><span>Schedule</span><b>${t.fixedSchedule===false?'Flexible':esc((t.startTime||'08:00')+'–'+(t.homeTime||'16:00'))}</b></div><div class="report-kpi"><span>Last event</span><b>${esc(st.time||'—')}</b></div><div class="report-kpi"><span>Email</span><b>${esc(t.email?'Set':'—')}</b></div></div><div class="panel"><h3>Today</h3>${bar('Present',teacherStatus(uid)==='AT_SCHOOL'||teacherStatus(uid)==='RETURNED'?100:0)}${bar('Late',teacherStatus(uid)==='LATE'?100:0)}${bar('Temporary',teacherStatus(uid)==='LEFT_TEMP'?100:0)}${bar('Final exit',teacherStatus(uid)==='LEFT_FINAL'?100:0)}</div>`;$('detailModal').classList.remove('hidden')}
function closeModal(id){$(id).classList.add('hidden')}window.closeModal=closeModal;window.openReport=openReport;window.openTeacherReport=openTeacherReport;window.editStudent=editStudent;window.editTeacher=editTeacher;window.deleteStudent=deleteStudent;window.deleteTeacher=deleteTeacher;window.setException=setException;window.clearException=clearException;window.setTeacherException=setTeacherException;window.clearTeacherException=clearTeacherException;
async function saveSettings(){if(!isAdmin())return;await db.ref('settings').update({morningOpen:$('setMorningOpen').value,schoolStart:$('setSchoolStart').value,homeTime:$('setHomeTime').value,eveningClose:$('setEveningClose').value,scanInterval:Number($('setScanInterval').value||60)});toast('Timing saved; machine will refresh automatically')}
async function saveNotificationSettings(){if(!isAdmin())return;await db.ref('settings').update({adminNotifyEmail:$('setAdminEmail').value.trim(),notifyAdmin:$('setNotifyAdmin').checked,notifyTeachers:$('setNotifyTeachers').checked,eventArrival:$('evArrival').checked,eventLate:$('evLate').checked,eventExit:$('evExit').checked,eventReturn:$('evReturn').checked,eventSick:$('evSick').checked,eventTeacher:$('evTeacher').checked});toast('Notification settings saved')}
async function saveUserRole(){if(!isAdmin())return;const uid=$('userUid').value.trim();if(!uid)return toast('Enter Firebase Auth UID');await db.ref('users/'+uid).update({role:$('userRole').value,active:true,updatedAt:new Date().toISOString()});toast('Role saved')}
async function processQueue(){if(!isAdmin()||!window.emailjs||EMAILJS_PUBLIC_KEY.startsWith('YOUR_'))return;for(const [id,n] of Object.entries(notifications)){if(n.sent||(!n.failed&&n.attempts>0))continue;if(n.failed&&(Date.now()-(n.lastAttempt||0)<60000))continue;await sendQueued(id,true)}}
async function sendQueued(id,silent=false){if(!isAdmin())return;const snap=await db.ref('notificationQueue/'+id).once('value'),n=snap.val();if(!n||n.sent)return;const attempts=Number(n.attempts||0)+1;await db.ref('notificationQueue/'+id).update({attempts,lastAttempt:Date.now(),failed:false});try{await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,{to_email:n.to_email||n.email,name:n.name||n.student_name||'',message:n.message||'',type:n.type||'Attendance',event:n.event||n.action||''});await db.ref('notificationQueue/'+id).update({sent:true,failed:false,status:'sent',sentAt:Date.now()});if(!silent)toast('Email sent')}catch(e){await db.ref('notificationQueue/'+id).update({failed:true,status:'failed',error:String(e.message||e),lastAttempt:Date.now()});if(!silent)toast('Email failed; kept for retry')}}
window.sendQueued=sendQueued;
async function retryFailed(){for(const [id,n] of Object.entries(notifications))if(n.failed&&!n.sent)await sendQueued(id);toast('Retry cycle finished')}
async function cleanupSent(manual=true){if(!isAdmin())return;const cutoff=Date.now()-24*3600*1000;for(const [id,n] of Object.entries(notifications)){if(n.sent&&n.sentAt&&n.sentAt<cutoff)await db.ref('notificationQueue/'+id).remove()}if(manual)toast('Old sent notifications cleaned; failed items were kept')}
window.retryFailed=retryFailed;window.cleanupSent=cleanupSent;
function rowsToCSV(tableId){const t=$(tableId);return [...t.querySelectorAll('tr')].map(r=>[...r.children].map(c=>'"'+c.innerText.replaceAll('"','""')+'"').join(',')).join('\n')}
function downloadTable(id,name){const blob=new Blob([rowsToCSV(id)],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadStudents(){downloadTable('studentsTable','students.csv')}function downloadTeachers(){downloadTable('teachersTable','teachers.csv')}window.downloadTable=downloadTable;window.downloadStudents=downloadStudents;window.downloadTeachers=downloadTeachers;
['studentSearch','teacherSearch','morningSearch','afternoonSearch'].forEach(id=>$(id).addEventListener('input',renderAll));['morningFilter','afternoonFilter'].forEach(id=>$(id).addEventListener('change',renderAll));
